/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class crixec_app_imagefactory_utils_NativeUtils */

#ifndef _Included_crixec_app_imagefactory_utils_NativeUtils
#define _Included_crixec_app_imagefactory_utils_NativeUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     crixec_app_imagefactory_utils_NativeUtils
 * Method:    unpackbootimg
 * Signature: ([Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_crixec_app_imagefactory_utils_NativeUtils_unpackbootimg
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     crixec_app_imagefactory_utils_NativeUtils
 * Method:    repackbootimg
 * Signature: ([Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_crixec_app_imagefactory_utils_NativeUtils_repackbootimg
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     crixec_app_imagefactory_utils_NativeUtils
 * Method:    unpackapp
 * Signature: ([Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_crixec_app_imagefactory_utils_NativeUtils_unpackapp
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     crixec_app_imagefactory_utils_NativeUtils
 * Method:    unpackcpb
 * Signature: ([Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_crixec_app_imagefactory_utils_NativeUtils_unpackcpb
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     crixec_app_imagefactory_utils_NativeUtils
 * Method:    simg2img
 * Signature: ([Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_crixec_app_imagefactory_utils_NativeUtils_simg2img
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     crixec_app_imagefactory_utils_NativeUtils
 * Method:    copyright
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_crixec_app_imagefactory_utils_NativeUtils_copyright
  (JNIEnv *, jclass);

/*
 * Class:     crixec_app_imagefactory_utils_NativeUtils
 * Method:    minigzip
 * Signature: ([Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_crixec_app_imagefactory_utils_NativeUtils_minigzip
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     crixec_app_imagefactory_utils_NativeUtils
 * Method:    checkWorksapce
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_crixec_app_imagefactory_utils_NativeUtils_checkWorksapce
  (JNIEnv *, jclass, jstring);

/*
 * Class:     crixec_app_imagefactory_utils_NativeUtils
 * Method:    cat
 * Signature: ([Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_crixec_app_imagefactory_utils_NativeUtils_cat
  (JNIEnv *, jclass, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
